#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""scaffold_project.py — 软件工程项目脚手架生成器

根据选定的开发模式，为新建软件项目生成标准化的目录骨架与初始工程文档，
将软件工程生命周期规范落地为可执行的工程结构。

用法:
    python3 scaffold_project.py --name <项目名> [--model <模式>] [--path <目录>] [--no-docs]

参数:
    --name    项目名称（必填），同时作为根目录名与包名
    --model   开发模式: waterfall | prototype | incremental | spiral | agile (默认 agile)
    --path    生成目标目录 (默认: ./<name>)
    --no-docs 不生成工程文档（仅目录骨架）

示例:
    python3 scaffold_project.py --name mstores --model agile
    python3 scaffold_project.py --name bank-core --model waterfall --path /tmp/proj
"""

import argparse
import os
import sys

MODELS = ["waterfall", "prototype", "incremental", "spiral", "agile"]

MODEL_DESC = {
    "waterfall": "瀑布模型：需求明确、变化少，顺序推进、文档齐全",
    "prototype": "原型模型：需求不明确，先快速做原型与用户确认",
    "incremental": "增量模型：按优先级分批交付可用功能",
    "spiral": "螺旋模型：大型高风险，风险驱动迭代",
    "agile": "敏捷开发：需求变化快，小步快跑持续交付",
}

# 各模式对应的目录骨架（相对项目根）
MODEL_LAYOUT = {
    "waterfall": {
        "docs": ["01-可行性研究", "02-需求分析", "03-概要设计",
                 "04-详细设计", "05-编码实现", "06-软件测试",
                 "07-部署", "08-维护"],
        "src": ["main"],
        "tests": ["unit", "integration"],
    },
    "prototype": {
        "docs": ["需求澄清", "正式需求"],
        "prototype": ["v1", "v2"],
        "src": ["main"],
        "tests": ["unit"],
    },
    "incremental": {
        "docs": ["架构设计", "增量规划"],
        "increments": ["inc-1-core", "inc-2-advanced"],
        "src": ["main"],
        "tests": ["unit", "integration", "regression"],
    },
    "spiral": {
        "docs": ["风险登记册"],
        "iterations": ["iter-1", "iter-2", "iter-3"],
        "prototype": ["risk-spike"],
        "src": ["main"],
        "tests": ["unit"],
    },
    "agile": {
        "docs": ["backlog"],
        "sprints": ["sprint-01", "sprint-02"],
        "src": ["main"],
        "tests": ["unit", "integration", "e2e"],
    },
}


def render_readme(name, model):
    return f"""# {name}

> 开发模式：**{model}** — {MODEL_DESC[model]}

本工程由软件工程技能（software-engineering）脚手架自动生成，遵循该模式的
生命周期节奏进行开发。详细执行细则见技能 `references/development-models.md`。

## 工程结构

{render_tree(name, model)}

## 当前模式工作流

- 模式：{model}
- 适用：{MODEL_DESC[model]}

请按该模式对应的阶段/迭代推进，并在各阶段产出对应文档（见 `docs/`）。

## 切换模式

如需在开发过程中切换模式，按软件工程技能的「模式切换矩阵」调整后续结构即可，
已有产出物（文档、代码、测试）应予以保留。

---
Generated by software-engineering skill · scaffold_project.py
"""


def render_tree(name, model):
    layout = MODEL_LAYOUT[model]
    lines = [name + "/"]
    for top in layout:
        lines.append(f"├── {top}/")
        for sub in layout[top]:
            lines.append(f"│   ├── {sub}/")
    lines.append("└── README.md")
    return "\n".join(lines)


def render_srs(name):
    return f"""# 软件需求规格说明书（SRS）— {name}

> 模板来源：software-engineering 技能 assets/srs-template.md，按项目补全 <...>

## 1. 引言
### 1.1 目的
<描述本文档目的>

### 1.2 范围
<系统名称、解决问题、目标用户、边界>

## 2. 总体描述
### 2.1 产品视角
<系统在业务中的位置>

### 2.2 用户特征
| 角色 | 描述 | 场景 |
|------|------|------|
| <角色> | <描述> | <场景> |

## 3. 具体需求
### 3.1 功能需求
| 编号 | 描述 | 优先级 | 来源 |
|------|------|-------|------|
| REQ-F-001 | <功能> | 高 | <用户> |

### 3.2 非功能需求
- 性能：<响应时间/吞吐>
- 安全：<认证/授权/加密>
- 可靠性：<可用性 SLA>

## 4. 需求追踪矩阵
| 编号 | 优先级 | 对应设计 | 测试用例 |
|------|-------|---------|---------|
| REQ-F-001 | 高 | | |
"""


def render_design(name, model):
    return f"""# 设计说明书 — {name}

> 模式：{model}。模板来源：software-engineering 技能 assets/design-doc-template.md

## 1. 引言
目的 / 范围 / 参考资料：软件需求规格说明书（SRS）

## 2. 总体设计
### 2.1 系统架构
<架构图 + 说明>

### 2.2 模块划分
| 模块 | 职责 | 依赖 |
|------|------|------|
| <模块> | <职责> | <依赖> |

### 2.3 技术选型
| 层面 | 选型 | 理由 |
|------|------|------|
| 语言/框架 | | |
| 数据库 | | |

## 3. 数据库设计
<ER 图 + 表结构>

## 4. 接口设计
<模块间/外部接口>

## 5. 安全与性能
<认证、缓存、索引、限流>
"""


def render_test_plan(name, model):
    return f"""# 测试计划 — {name}

> 模式：{model}。参考：software-engineering 技能 references/testing-maintenance.md

## 1. 测试目标与范围
<目标、覆盖的功能与非功能需求>

## 2. 测试层次
- [ ] 单元测试（unit/）
- [ ] 集成测试（integration/）
- [ ] 系统测试
- [ ] 验收测试

## 3. 测试类型
- 黑盒：等价类划分、边界值分析
- 白盒：分支/路径覆盖
- 灰盒：集成与 API

## 4. 环境与进度
<环境、资源、排期>

## 5. 缺陷与验收
- 严重程度：致命/严重/一般/轻微
- 验收标准：<何时可发布>
"""


def main():
    parser = argparse.ArgumentParser(description="软件工程项目脚手架生成器")
    parser.add_argument("--name", required=True, help="项目名称")
    parser.add_argument("--model", default="agile", choices=MODELS,
                        help="开发模式 (默认 agile)")
    parser.add_argument("--path", default=None, help="生成目标目录 (默认 ./<name>)")
    parser.add_argument("--no-docs", action="store_true", help="仅生成目录骨架")
    args = parser.parse_args()

    root = args.path or os.path.join(os.getcwd(), args.name)
    if os.path.exists(root) and os.listdir(root):
        sys.exit(f"错误：目标目录已存在且非空: {root}")

    layout = MODEL_LAYOUT[args.model]
    created = []

    # 创建目录骨架
    for top, subs in layout.items():
        top_dir = os.path.join(root, top)
        os.makedirs(top_dir, exist_ok=True)
        created.append(top + "/")
        for sub in subs:
            sub_dir = os.path.join(top_dir, sub)
            os.makedirs(sub_dir, exist_ok=True)
            # 为每个子目录放置 .gitkeep，确保空目录纳入版本控制
            open(os.path.join(sub_dir, ".gitkeep"), "w").close()
            created.append(f"{top}/{sub}/")

    # 生成文档
    if not args.no_docs:
        docs = {
            "README.md": render_readme(args.name, args.model),
            os.path.join("docs", "SRS.md"): render_srs(args.name),
            os.path.join("docs", "design.md"): render_design(args.name, args.model),
            os.path.join("docs", "test-plan.md"): render_test_plan(args.name, args.model),
        }
        for rel, content in docs.items():
            full = os.path.join(root, rel)
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w", encoding="utf-8") as f:
                f.write(content)
            created.append(rel)

    # 生成 src 占位入口
    entry = os.path.join(root, "src", "main", "README.md")
    os.makedirs(os.path.dirname(entry), exist_ok=True)
    with open(entry, "w", encoding="utf-8") as f:
        f.write(f"# 源码入口 — {args.name}\n\n在此编写可维护、可复用的代码。\n")

    print(f"✅ 已生成项目骨架: {root}")
    print(f"   开发模式: {args.model} — {MODEL_DESC[args.model]}")
    print(f"   文件/目录数: {len(created)}")
    for c in created:
        print(f"   + {c}")


if __name__ == "__main__":
    main()
